CREATE TABLE IF NOT EXISTS etl_run_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    message TEXT
);

CREATE TABLE IF NOT EXISTS posts_raw (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(512) NOT NULL,
    body TEXT NOT NULL,
    ingested_run_id VARCHAR(64) NOT NULL,
    ingested_at_epoch_ms BIGINT NOT NULL
);